---
- hosts: nodocker
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus-community/ansible
        state: present
    - name: Start Prometheus
      service:
        name: prometheus-community/ansible
        state: started
        enabled: yes
