---
- name: Pull and run n8n Docker container
  hosts: arbatravel
  gather_facts: yes
  become: yes

  vars:
    n8n_username: ***
    n8n_password: ***

  tasks:
    - name: Pull n8n Docker image
      docker_image:
        name: n8nio/n8n
        state: present
        source: pull

    - name: Create directory for n8n data
      file:
        path: /path/to/n8n/data
        state: directory
        mode: "0755"

    - name: Run n8n Docker container
      docker_container:
        name: n8n
        image: n8nio/n8n
        state: started
        restart_policy: always
        env:
          N8N_BASIC_AUTH_USER: "{{ n8n_username }}"
          N8N_BASIC_AUTH_PASSWORD: "{{ n8n_password }}"
        volumes:
          - /path/to/n8n/data:/home/node/.n8n
        ports:
          - "5678:5678"
   
