---
- hosts: jenkins-installation
  become: true
  vars:
    prometheus_server_ip: "{{ ip_address }}"
    ansible_ssh_host: "{{ ip_address }}"
    ansible_ssh_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_ssh_port: "6262"
  roles:
    - prometheus
  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
