---
- hosts: jenkins-installation
  become: true
  vars:
    prometheus_server_ip: "{{ ip_address }}"
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
  roles:
    - prometheus
  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
