---
- name: Clone Docker image from GitHub
  hosts: all
  tasks:
    - name: Clone GitHub repository
      git:
        repo: https://github.com/aimanhaziqmy/my_app_fastapi_1.git
        dest: ~/my_app
        clone: yes
        update: yes

    - name: Build Docker image
      docker_image:
        name: my_app
        source: build
        build:
          path: ~/my_app
        tag: v1

    - name: Run Docker container
      docker_container:
        name: my_app
        image: my_app:v1
        ports:
          - "7000:80"
        restart_policy: unless-stopped
