- name: Create Prometheus directory
  become: true
  file:
    path: ~/Prometheus
    state: directory

- name: Copy prometheus.yml configuration file
  become: true
  template:
    src:  prometheus.yml.j2
    dest: ~/Prometheus/prometheus.yml

- name: Install and run Node Exporter using Docker
  become: true
  docker_container:
    name: node_exporter
    image: prom/node-exporter
    restart_policy: always
    ports:
      - "9200:9100"

- name: Pull cAdvisor image
  docker_image:
    name: google/cadvisor:latest
    source: pull

# cAdvisor with min of 1% - 2% of CPU usage
- name: Create cAdvisor container
  docker_container:
    name: cadvisor
    image: google/cadvisor:latest
    restart_policy: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    command:
      - '-housekeeping_interval=55s'
      - '-docker_only=true'
      - '--disable_metrics=disk,tcp,udp,percpu,sched,process'
      - '-allow_dynamic_housekeeping=false'
      - '--store_container_labels=false'
      - '--event_storage_event_limit=default=0'
      - '--event_storage_age_limit=default=0'
      - '--global_housekeeping_interval=55s'
      - '--storage_duration=1m0s'
    security_opts:
      - no-new-privileges:true
    ports:
      - "8090:8080"


- name: Install and run Prometheus using Docker
  become: true
  docker_container:
    name: prometheus
    image: prom/prometheus
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - ~/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

- name: Update Prometheus configuration
  lineinfile:
    path: ~/Prometheus/prometheus.yml
    line: "  - job_name : 'cadvisor'"
    insertafter: "^scrape_configs:"
  notify: restart prometheus

- name: Allow incoming connections on port 9100 for Node Exporter
  become: true
  ufw:
    rule: allow
    port: 9100

- name: Allow incoming connections on port 9090 for Prometheus
  become: true
  ufw:
    rule: allow
    port: 9090

- name: Allow incoming connections on port 8080 for cAdvisor
  become: true
  ufw:
    rule: allow
    port: 8090
