version: '3'
services: 
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    command:
      - '-housekeeping_interval=30s'
      - '-docker_only=true'
      - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
    security_opt:
      - no-new-privileges:true
    ports:
      - "8090:8080"
